
package jmp.yury.kiryla.web_services_task2.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RandomNumberGeneratorService", targetNamespace = "http://service.web_services_task2.kiryla.yury.jmp/", wsdlLocation = "http://localhost:8080/soap_service?wsdl")
public class RandomNumberGeneratorService
    extends Service
{

    private final static URL RANDOMNUMBERGENERATORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jmp.yury.kiryla.web_services_task2.service.RandomNumberGeneratorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jmp.yury.kiryla.web_services_task2.service.RandomNumberGeneratorService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/soap_service?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/soap_service?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RANDOMNUMBERGENERATORSERVICE_WSDL_LOCATION = url;
    }

    public RandomNumberGeneratorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandomNumberGeneratorService() {
        super(RANDOMNUMBERGENERATORSERVICE_WSDL_LOCATION, new QName("http://service.web_services_task2.kiryla.yury.jmp/", "RandomNumberGeneratorService"));
    }

    /**
     * 
     * @return
     *     returns RandomNumberGenerator
     */
    @WebEndpoint(name = "RandomNumberGeneratorPort")
    public RandomNumberGenerator getRandomNumberGeneratorPort() {
        return super.getPort(new QName("http://service.web_services_task2.kiryla.yury.jmp/", "RandomNumberGeneratorPort"), RandomNumberGenerator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomNumberGenerator
     */
    @WebEndpoint(name = "RandomNumberGeneratorPort")
    public RandomNumberGenerator getRandomNumberGeneratorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web_services_task2.kiryla.yury.jmp/", "RandomNumberGeneratorPort"), RandomNumberGenerator.class, features);
    }

}
