
package jmp.yury.kiryla.web_services_task2.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RandomNumberGenerator", targetNamespace = "http://service.web_services_task2.kiryla.yury.jmp/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RandomNumberGenerator {


    /**
     * 
     * @param lowerBound
     * @param upperBound
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int randomNumber(
        @WebParam(name = "lowerBound", partName = "lowerBound")
        int lowerBound,
        @WebParam(name = "upperBound", partName = "upperBound")
        int upperBound);

}
