create table USERS(
	ID 				INT 			AUTO_INCREMENT,
	NAME 			VARCHAR(50) 	NOT NULL,
	PRIMARY KEY (ID), 
	UNIQUE (NAME)
);

create table AUDITORIUMS(
	ID				INT				AUTO_INCREMENT,
	NAME			VARCHAR(50)		NOT NULL,
	PRIMARY KEY (ID), 
	UNIQUE (NAME)
);

create table EVENTS(
	ID 				INT 			AUTO_INCREMENT,
	NAME 			VARCHAR(50) 	NOT NULL,
	AUDITORIUM_ID	INT				NOT NULL,
	DATE			DATE			NOT NULL,
	START_TIME		TIME			NOT NULL,
	END_TIME		TIME			NOT NULL,
	PRIMARY KEY (ID), 
	UNIQUE (NAME),
	FOREIGN KEY (AUDITORIUM_ID) REFERENCES AUDITORIUMS(ID)
);

create table TICKETS(
	ID				INT				AUTO_INCREMENT,
	USER_ID			INT				NOT NULL,
	EVENT_ID		INT				NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (USER_ID,EVENT_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
	FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID)
);